name: Windows RDP via Tailscale (A)

on:
  workflow_dispatch:
    inputs:
      fixed_hostname:
        description: "Tailscale hostname (MagicDNS)"
        required: false
        default: "gha-rdp"
      rdp_user:
        description: "RDP username"
        required: false
        default: "ghauser"
      keep_minutes:
        description: "Keep alive minutes (<=350)"
        required: false
        default: "350"
  workflow_run:
    workflows: ["Windows RDP via Tailscale (B)"]
    types: [completed]

jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: 360
    env:
      FIXED_HOSTNAME: ${{ github.event.inputs.fixed_hostname || 'gha-rdp' }}
      RDP_USER:       ${{ github.event.inputs.rdp_user || 'ghauser' }}
      RDP_PASSWORD:   ${{ secrets.RDP_PASSWORD }}            # <-- Secret
      TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}  # <-- Secret
      KEEP_MINUTES:   ${{ github.event.inputs.keep_minutes || '350' }}

    steps:
      - name: Install Tailscale
        shell: pwsh
        run: |
          $msi  = "$env:TEMP\tailscale.msi"
          Invoke-WebRequest "https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi" -OutFile $msi
          Start-Process msiexec.exe -ArgumentList "/i `"$msi`" /qn /norestart" -Wait
          Remove-Item $msi -Force
          & "$env:ProgramFiles\Tailscale\tailscale.exe" version

      - name: Enable RDP + user + firewall
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server' -Name fDenyTSConnections -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop" | Out-Null
          $sec = ConvertTo-SecureString $env:RDP_PASSWORD -AsPlainText -Force
          if (-not (Get-LocalUser -Name $env:RDP_USER -ErrorAction SilentlyContinue)) {
            New-LocalUser -Name $env:RDP_USER -Password $sec -AccountNeverExpires
          } else {
            Set-LocalUser -Name $env:RDP_USER -Password $sec -AccountNeverExpires:$true
            Enable-LocalUser -Name $env:RDP_USER
          }
          Add-LocalGroupMember -Group "Administrators" -Member $env:RDP_USER -ErrorAction SilentlyContinue
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member $env:RDP_USER -ErrorAction SilentlyContinue

      - name: Tailscale up (fixed hostname)
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $ts = "$env:ProgramFiles\Tailscale\tailscale.exe"
          & $ts up --authkey "$env:TAILSCALE_AUTH_KEY" --hostname "$env:FIXED_HOSTNAME" --reset
          if ($LASTEXITCODE -ne 0) { throw "tailscale up failed" }

          $ip4 = & $ts ip -4
          $ip6 = & $ts ip -6
          Write-Host "================ RDP CONNECT ================"
          Write-Host "MagicDNS name : $env:FIXED_HOSTNAME"
          Write-Host "IPv4          : $ip4"
          Write-Host "IPv6          : $ip6"
          Write-Host "mstsc         : mstsc /v:$($env:FIXED_HOSTNAME)"
          Write-Host "Username      : $env:RDP_USER"
          Write-Host "Password      : ******  (GitHub Secret RDP_PASSWORD)"
          Write-Host "============================================"

      - name: Keep alive
        shell: pwsh
        run: |
          $mins = [int]$env:KEEP_MINUTES
          if ($mins -gt 350) { $mins = 350 }
          $until = (Get-Date).AddMinutes($mins)
          while ((Get-Date) -lt $until) {
            Write-Host "[$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')] RDP alive…"
            Start-Sleep -Seconds 300
          }
